myapp/urls.py
from django.urls import path
from . import views
from django.conf import settings
from  django.conf.urls.static import static
app_name='myapp'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('menu.html', views.menu_view, name='menu_html'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('book/', views.book_table, name='book'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('order/', views.OrderView.as_view(), name='order'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('cart/add/<str:item_id>/', views.add_to_cart, name='cart_add'),
    path('login/',views.login_html,name='login'),
    path('signup/',views.signup,name='signup'),
    path('log_out/',views.log_out,name='log_out'),
    path('profile/',views.my_account,name='profile'),
    path('update_user',views.update_user,name='update_user'),
    path('update_password',views.update_password,name='update_password'),
    path('buy/<int:item_id>/', views.buy_now, name='buy_now'),
    path('cart/<int:p_id>/<int:qty>/',views.add_cart,name='cart'),
    path('cartitems/', views.show_cart, name='show_cart'),
    path('delete-cart-item/<int:product_id>/', views.delete_cart_item, name='delete_cart_item'),
    path('decrease-quantity/<int:product_id>/', views.decrease_quantity, name='decrease_quantity'),
    path('increase-quantity/<int:product_id>/', views.increase_quantity, name='increase_quantity'),
    path('checkout/', views.checkout, name='checkout'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.urls import path
# from . import views

# app_name = 'myapp'

# urlpatterns = [
#     path('cartitems/', views.show_cart, name='show_cart'),
#     path('delete-cart-item/<int:product_id>/', views.delete_cart_item, name='delete_cart_item'),
#     path('increase-quantity/<int:product_id>/', views.increase_quantity, name='increase_quantity'),
#     path('decrease-quantity/<int:product_id>/', views.decrease_quantity, name='decrease_quantity'),
# ]

myapp1/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='myapp1'
urlpatterns = [
    path('', views.index, name='home'),
    path('add_food', views.add_food, name='add_food'),
    path('food', views.view_food, name='view_food'),
    path('update_food', views.update_food, name='update_food'),
    path('dashboard/delete_food/<int:f_id>/', views.delete_food, name='delete_food'),
    path('view_users/', views.view_users, name='view_users'),
    path('cart/add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('dashboard/add_coupon/', views.add_coupon, name='add_coupon'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from  django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard',include ('myapp1.urls')),
    path('',include ('myapp.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_URL)

myapp1/models.py
from django.db import models


class FoodItem(models.Model):
    name = models.CharField(max_length=100,blank=True,null=True)
    price = models.IntegerField(max_length=10,blank=True,null=True)
    image = models.ImageField(upload_to='food_images/',blank=True,null=True)
    description = models.TextField(blank=True, null=True) 
    def __str__(self):
        return self.name
    

class Coupon(models.Model):
    coupon_code = models.CharField(max_length=20, unique=True)
    discount_percent = models.PositiveIntegerField(blank=True, null=True)
    start_date = models.DateField(blank=True, null=True)
    end_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return f"{self.coupon_code} - {self.discount_percent}%"

myapp1/forms.py
from django import forms
from .models import FoodItem

class FoodItemForm(forms.ModelForm):
    class Meta:
        model = FoodItem
        fields = ['name', 'image']

myapp1/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import FoodItem
from .forms import FoodItemForm
from myapp.models import MyUser  
from django.contrib.auth.decorators import login_required
from myapp.models import Cart
from .models import Coupon
from django.contrib import messages





def index(request):
    """Render the index page."""
    return render(request, 'dash/index.html')


def add_food(request):
    """Add a new food item."""
    if request.method == 'POST':
        name = request.POST.get('name')
        price = request.POST.get('price')
        image = request.FILES.get('image')
        description = request.POST.get('description')
        print(name, price, image)

        food = FoodItem(name=name, price=price, image=image, description=description)
        food.save()

        return redirect('myapp1:add_food')
    return render(request, 'dash/add_food.html')


def dashboard(request):
    """Render the dashboard with all food items."""
    food_items = FoodItem.objects.all()
    context = {
        'food_items': food_items
    }
    return render(request, 'dashboard/dashboard.html', context)


def view_food(request):
    """View details of a specific food item."""
    item = FoodItem.objects.all()
    
    return render(request, 'dash/views_item.html', {'items': item})

def update_food(request):
    if request.method == 'POST':
        i_id=int(request.POST.get('itemId'))
        new_name=request.POST.get('name')
        new_price=request.POST.get('price')
        new_description=request.POST.get('description')
        new_image=request.FILES.get('image')
        prdt=FoodItem.objects.get(id=i_id)
        prdt.name=new_name
        prdt.description=new_description
        prdt.price=new_price
        print(new_name,new_price,new_description,'okkkkkkkkkkkkkkkkkkkkk')
       


        if new_image:
            prdt.image=new_image
        prdt.save()
        
        return redirect('myapp1:view_food')
def delete_food(request,f_id):
    food=FoodItem.objects.get(id=f_id)
    food.delete()
    return redirect('myapp1:view_food')



def view_users(request):
    users = MyUser.objects.all()
    return render(request, 'dash/view_user.html', {'users': users})




@login_required
def add_cart(request, product_id):
    if request.method == "POST":
        user = request.user
        product = get_object_or_404(FoodItem, id=product_id)
        quantity = int(request.POST.get('quantity', 1))

        
        cart_item, created = Cart.objects.get_or_create(user=user, product=product)
        if not created:
            cart_item.quantity += quantity  
        else:
            cart_item.quantity = quantity   
        cart_item.save()

        return redirect('cart_page')  

    
    return redirect('home')


def add_coupon(request):
    if request.method == 'POST':
        
        code = request.POST.get('coupon_code')
        discount = request.POST.get('discount_percent')
        start = request.POST.get('start_date')
        end = request.POST.get('end_date')
        coupon = Coupon(coupon_code=code,discount_percent=discount,start_date=start,end_date=end)

        coupon.save()

        return redirect('myapp1:add_coupon')  

    return render(request, 'dash/add_coupon.html')

     








     
        


    
        

    

myapp1/templates/dash/_footer.html
<footer class="footer">
          <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © 2021.  Premium <a href="https://www.bootstrapdash.com/" target="_blank">Bootstrap admin template</a> from BootstrapDash. All rights reserved.</span>
            <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Hand-crafted & made with <i class="ti-heart text-danger ml-1"></i></span>
          </div>
        </footer>

myapp1/templates/dash/_navbar.html
<nav class="navbar col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
      <div class="text-center navbar-brand-wrapper d-flex align-items-center justify-content-center">
        <a class="navbar-brand brand-logo mr-5" href="index.html"><img src="images/logo.svg" class="mr-2" alt="logo"/></a>
        <a class="navbar-brand brand-logo-mini" href="index.html"><img src="images/logo-mini.svg" alt="logo"/></a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center justify-content-end">
        <button class="navbar-toggler navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span class="icon-menu"></span>
        </button>
        <ul class="navbar-nav mr-lg-2">
          <li class="nav-item nav-search d-none d-lg-block">
            <div class="input-group">
              <div class="input-group-prepend hover-cursor" id="navbar-search-icon">
                <span class="input-group-text" id="search">
                  <i class="icon-search"></i>
                </span>
              </div>
              <input type="text" class="form-control" id="navbar-search-input" placeholder="Search now" aria-label="search" aria-describedby="search">
            </div>
          </li>
        </ul>
        <ul class="navbar-nav navbar-nav-right">
          <li class="nav-item dropdown">
            <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
              <i class="icon-bell mx-0"></i>
              <span class="count"></span>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list" aria-labelledby="notificationDropdown">
              <p class="mb-0 font-weight-normal float-left dropdown-header">Notifications</p>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-success">
                    <i class="ti-info-alt mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">Application Error</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Just now
                  </p>
                </div>
              </a>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-warning">
                    <i class="ti-settings mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">Settings</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    Private message
                  </p>
                </div>
              </a>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <div class="preview-icon bg-info">
                    <i class="ti-user mx-0"></i>
                  </div>
                </div>
                <div class="preview-item-content">
                  <h6 class="preview-subject font-weight-normal">New user registration</h6>
                  <p class="font-weight-light small-text mb-0 text-muted">
                    2 days ago
                  </p>
                </div>
              </a>
            </div>
          </li>
          <li class="nav-item nav-profile dropdown">
            <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown" id="profileDropdown">
              <img src="images/faces/face28.jpg" alt="profile"/>
            </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="profileDropdown">
              <a class="dropdown-item">
                <i class="ti-settings text-primary"></i>
                Settings
              </a>
              <a class="dropdown-item">
                <i class="ti-power-off text-primary"></i>
                Logout
              </a>
            </div>
          </li>
          <li class="nav-item nav-settings d-none d-lg-flex">
            <a class="nav-link" href="#">
              <i class="icon-ellipsis"></i>
            </a>
          </li>
        </ul>
        <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
          <span class="icon-menu"></span>
        </button>
      </div>
    </nav>

myapp1/templates/dash/_settings-panel.html
<div class="theme-setting-wrapper">
        <div id="settings-trigger"><i class="ti-settings"></i></div>
        <div id="theme-settings" class="settings-panel">
          <i class="settings-close ti-close"></i>
          <p class="settings-heading">SIDEBAR SKINS</p>
          <div class="sidebar-bg-options selected" id="sidebar-light-theme"><div class="img-ss rounded-circle bg-light border mr-3"></div>Light</div>
          <div class="sidebar-bg-options" id="sidebar-dark-theme"><div class="img-ss rounded-circle bg-dark border mr-3"></div>Dark</div>
          <p class="settings-heading mt-2">HEADER SKINS</p>
          <div class="color-tiles mx-0 px-4">
            <div class="tiles success"></div>
            <div class="tiles warning"></div>
            <div class="tiles danger"></div>
            <div class="tiles info"></div>
            <div class="tiles dark"></div>
            <div class="tiles default"></div>
          </div>
        </div>
      </div>
      <div id="right-sidebar" class="settings-panel">
        <i class="settings-close ti-close"></i>
        <ul class="nav nav-tabs border-top" id="setting-panel" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="todo-tab" data-toggle="tab" href="#todo-section" role="tab" aria-controls="todo-section" aria-expanded="true">TO DO LIST</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" id="chats-tab" data-toggle="tab" href="#chats-section" role="tab" aria-controls="chats-section">CHATS</a>
          </li>
        </ul>
        <div class="tab-content" id="setting-content">
          <div class="tab-pane fade show active scroll-wrapper" id="todo-section" role="tabpanel" aria-labelledby="todo-section">
            <div class="add-items d-flex px-3 mb-0">
              <form class="form w-100">
                <div class="form-group d-flex">
                  <input type="text" class="form-control todo-list-input" placeholder="Add To-do">
                  <button type="submit" class="add btn btn-primary todo-list-add-btn" id="add-task">Add</button>
                </div>
              </form>
            </div>
            <div class="list-wrapper px-3">
              <ul class="d-flex flex-column-reverse todo-list">
                <li>
                  <div class="form-check">
                    <label class="form-check-label">
                      <input class="checkbox" type="checkbox">
                      Team review meeting at 3.00 PM
                    </label>
                  </div>
                  <i class="remove ti-close"></i>
                </li>
                <li>
                  <div class="form-check">
                    <label class="form-check-label">
                      <input class="checkbox" type="checkbox">
                      Prepare for presentation
                    </label>
                  </div>
                  <i class="remove ti-close"></i>
                </li>
                <li>
                  <div class="form-check">
                    <label class="form-check-label">
                      <input class="checkbox" type="checkbox">
                      Resolve all the low priority tickets due today
                    </label>
                  </div>
                  <i class="remove ti-close"></i>
                </li>
                <li class="completed">
                  <div class="form-check">
                    <label class="form-check-label">
                      <input class="checkbox" type="checkbox" checked>
                      Schedule meeting for next week
                    </label>
                  </div>
                  <i class="remove ti-close"></i>
                </li>
                <li class="completed">
                  <div class="form-check">
                    <label class="form-check-label">
                      <input class="checkbox" type="checkbox" checked>
                      Project review
                    </label>
                  </div>
                  <i class="remove ti-close"></i>
                </li>
              </ul>
            </div>
            <h4 class="px-3 text-muted mt-5 font-weight-light mb-0">Events</h4>
            <div class="events pt-4 px-3">
              <div class="wrapper d-flex mb-2">
                <i class="ti-control-record text-primary mr-2"></i>
                <span>Feb 11 2018</span>
              </div>
              <p class="mb-0 font-weight-thin text-gray">Creating component page build a js</p>
              <p class="text-gray mb-0">The total number of sessions</p>
            </div>
            <div class="events pt-4 px-3">
              <div class="wrapper d-flex mb-2">
                <i class="ti-control-record text-primary mr-2"></i>
                <span>Feb 7 2018</span>
              </div>
              <p class="mb-0 font-weight-thin text-gray">Meeting with Alisa</p>
              <p class="text-gray mb-0 ">Call Sarah Graves</p>
            </div>
          </div>
          <!-- To do section tab ends -->
          <div class="tab-pane fade" id="chats-section" role="tabpanel" aria-labelledby="chats-section">
            <div class="d-flex align-items-center justify-content-between border-bottom">
              <p class="settings-heading border-top-0 mb-3 pl-3 pt-0 border-bottom-0 pb-0">Friends</p>
              <small class="settings-heading border-top-0 mb-3 pt-0 border-bottom-0 pb-0 pr-3 font-weight-normal">See All</small>
            </div>
            <ul class="chat-list">
              <li class="list active">
                <div class="profile"><img src="images/faces/face1.jpg" alt="image"><span class="online"></span></div>
                <div class="info">
                  <p>Thomas Douglas</p>
                  <p>Available</p>
                </div>
                <small class="text-muted my-auto">19 min</small>
              </li>
              <li class="list">
                <div class="profile"><img src="images/faces/face2.jpg" alt="image"><span class="offline"></span></div>
                <div class="info">
                  <div class="wrapper d-flex">
                    <p>Catherine</p>
                  </div>
                  <p>Away</p>
                </div>
                <div class="badge badge-success badge-pill my-auto mx-2">4</div>
                <small class="text-muted my-auto">23 min</small>
              </li>
              <li class="list">
                <div class="profile"><img src="images/faces/face3.jpg" alt="image"><span class="online"></span></div>
                <div class="info">
                  <p>Daniel Russell</p>
                  <p>Available</p>
                </div>
                <small class="text-muted my-auto">14 min</small>
              </li>
              <li class="list">
                <div class="profile"><img src="images/faces/face4.jpg" alt="image"><span class="offline"></span></div>
                <div class="info">
                  <p>James Richardson</p>
                  <p>Away</p>
                </div>
                <small class="text-muted my-auto">2 min</small>
              </li>
              <li class="list">
                <div class="profile"><img src="images/faces/face5.jpg" alt="image"><span class="online"></span></div>
                <div class="info">
                  <p>Madeline Kennedy</p>
                  <p>Available</p>
                </div>
                <small class="text-muted my-auto">5 min</small>
              </li>
              <li class="list">
                <div class="profile"><img src="images/faces/face6.jpg" alt="image"><span class="online"></span></div>
                <div class="info">
                  <p>Sarah Graves</p>
                  <p>Available</p>
                </div>
                <small class="text-muted my-auto">47 min</small>
              </li>
            </ul>
          </div>
          <!-- chat tab ends -->
        </div>
      </div>

myapp1/templates/dash/add_coupon.html
{% extends 'dash/index.html' %}
{% block content %}
  <style>
    .coupon-wrapper {
      display: flex;
      justify-content: center;
      align-items: center;
      height: 100vh;
      background: linear-gradient(135deg, #0f2027, #203a43, #2c5364);
    }

    .coupon-form {
      background: rgba(255, 255, 255, 0.1);
      backdrop-filter: blur(10px);
      padding: 30px;
      border-radius: 16px;
      color: white;
      width: 100%;
      max-width: 420px;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.3);
    }

    .coupon-form h2 {
      text-align: center;
      margin-bottom: 24px;
      font-size: 22px;
      color: #fff;
    }

    .form-group {
      margin-bottom: 18px;
    }

    label {
      display: block;
      margin-bottom: 6px;
      font-weight: 500;
      color: #ddd;
    }

    input[type="text"],
    input[type="number"],
    input[type="date"] {
      width: 100%;
      padding: 10px 12px;
      border: 1px solid #888;
      border-radius: 8px;
      background-color: rgba(255, 255, 255, 0.15);
      color: #fff;
      font-size: 14px;
      outline: none;
    }

    input::placeholder {
      color: rgba(255, 255, 255, 0.6);
    }

    .btn-submit {
      width: 100%;
      padding: 12px;
      background-color: #00c9a7;
      color: white;
      border: none;
      border-radius: 8px;
      font-weight: bold;
      font-size: 16px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .btn-submit:hover {
      background-color: #00b18a;
    }

    .message {
      text-align: center;
      margin-bottom: 10px;
      font-weight: bold;
    }
  </style>

  <div class="coupon-wrapper">
    <form class="coupon-form" method="post">
      {% csrf_token %}
      <h2>🎟️ Add Coupon</h2>

      {% if messages %}
        <div class="message">
          {% for message in messages %}
            {% if message.tags == 'error' %}
              <p style="color: red;">{{ message }}</p>
            {% else %}
              <p style="color: lightgreen;">{{ message }}</p>
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}

      <div class="form-group">
        <label for="coupon_code">Coupon Code</label>
        <input type="text" name="coupon_code" id="coupon_code" placeholder="e.g. NEWUSER25" required>
      </div>

      <div class="form-group">
        <label for="discount_percent">Discount (%)</label>
        <input type="number" name="discount_percent" id="discount_percent" placeholder="e.g. 25" min="1" max="100" required>
      </div>

      <div class="form-group">
        <label for="start_date">Start Date</label>
        <input type="date" name="start_date" id="start_date" required>
      </div>

      <div class="form-group">
        <label for="end_date">End Date</label>
        <input type="date" name="end_date" id="end_date" required>
      </div>

      <button type="submit" class="btn-submit">Add Coupon</button>
    </form>
  </div>
{% endblock %}
  

myapp1/templates/dash/views_item.html
{% extends 'dash/index.html' %}
{% block content %}


  <style>
    body {
      font-family: 'Segoe UI', sans-serif;
      background: #f0f2f5;
      margin: 0;
      padding: 20px;
    }

    h1 {
      text-align: center;
      color: #2c3e50;
    }

    .table-container {
      max-width: 1000px;
      margin: auto;
      background: #fff;
      padding: 20px;
      border-radius: 12px;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.1);
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }

    th, td {
      padding: 12px 15px;
      border-bottom: 1px solid #ddd;
      text-align: center;
    }

    th {
      background-color: #2c3e50;
      color: white;
    }

    img {
      width: 80px;
      height: 60px;
      object-fit: cover;
      border-radius: 5px;
    }

    .btn-view {
      background-color: #3498db;
      color: white;
      padding: 6px 12px;
      border-radius: 5px;
      text-decoration: none;
      display: inline-block;
      font-size: 14px;
    }

    .btn-view i {
      margin-right: 5px;
    }

    .btn-view:hover {
      background-color: #2980b9;
    }

    .no-items {
      text-align: center;
      color: #888;
      padding: 20px;
    }

    .popup {
      display: none;
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.5);
      justify-content: center;
      align-items: center;
      z-index: 9999;
    }

    .popup-content {
      position: relative;
      background: #fff;
      padding: 20px;
      border-radius: 10px;
      width: 400px;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.2);
    }

    .popup-content h2 {
      margin-top: 0;
      color: #2c3e50;
      text-align: center;
    }

    .form-group {
      margin-bottom: 15px;
    }

    .form-group label {
      display: block;
      margin-bottom: 5px;
      color: #2c3e50;
    }

    .form-group input,
    .form-group textarea,
    .form-group input[type="file"] {
      width: 100%;
      padding: 8px;
      border: 1px solid #ddd;
      border-radius: 5px;
      box-sizing: border-box;
    }

    .btn-group {
      margin-top: 20px;
      display: flex;
      justify-content: space-between;
    }

    .btn-save,
    .btn-delete {
      padding: 8px 15px;
      border: none;
      border-radius: 5px;
      color: white;
      cursor: pointer;
    }

    .btn-save {
      background-color: #27ae60;
    }

    .btn-save:hover {
      background-color: #219653;
    }

    .btn-delete {
      background-color: #e74c3c;
    }

    .btn-delete:hover {
      background-color: #c0392b;
    }

    .close-btn {
      position: absolute;
      top: 10px;
      right: 15px;
      font-size: 24px;
      cursor: pointer;
      color: #888;
    }

    .close-btn:hover {
      color: #2c3e50;
    }
  </style>

  <div class="table-container">
    <h1>Available Food Items</h1>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Price (₹)</th>
          <th>Description</th>
          <th>Image</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <tr>
          <td>{{ item.name }}</td>
          <td>{{ item.price }}</td>
          <td>{{ item.description }}</td>
          <td><img src="{{ item.image.url }}" alt="{{ item.name }}"></td>
          <td>
            <a href="#" class="btn-view" onclick="openPopup('{{ item.id }}', '{{ item.name }}', '{{ item.price }}', '{{ item.description|escapejs }}', '{{ item.image.url }}')">
              <i class="fas fa-pen"></i> Edit
            </a>
          </td>
        </tr>
        {% empty %}
        <tr>
          <td colspan="5" class="no-items">No food items available.</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <!-- Popup Form -->
  <div id="popup" class="popup">
    <div class="popup-content">
      <span class="close-btn" onclick="closePopup()">&times;</span>
      <h2>Edit Food Item</h2>
      <form method="POST" action="{% url 'myapp1:update_food' %}"  enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" id="itemId" name="itemId">
        <div class="form-group">
          <label for="name">Name</label>
          <input type="text" id="name" name="name" required>
        </div>
        <div class="form-group">
          <label for="price">Price (₹)</label>
          <input type="number" id="price" name="price" step="0.01" required>
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <textarea id="description" name="description" rows="3" required></textarea>
        </div>
        <div class="form-group">
          <label for="image">Image</label>
          <input type="file" id="image" name="image">
          <img id="currentImage" src="" alt="Current Image" style="width: 100px; height: 75px; margin-top: 10px; display: none;">
        </div>
        <div class="btn-group">
          <button type="submit" class="btn-save">Save</button>
          
          <a id="myh" class="btn-delete" >Delete</a>
        </div>
      </form>
    </div>
  </div>

  <script>
    function openPopup(id, name, price, description, imageUrl) {
      document.getElementById('popup').style.display = 'flex';
      document.getElementById('itemId').value = id;
      document.getElementById('name').value = name;
      document.getElementById('price').value = price;
      document.getElementById('description').value = description;
    const baseUrl = "{% url 'myapp1:delete_food' 0 %}".replace('/0/', '/');
    document.getElementById('myh').href = `${baseUrl}${id}/`;

      const currentImage = document.getElementById('currentImage');
      currentImage.src = imageUrl;
      currentImage.style.display = imageUrl ? 'block' : 'none';
    }

    function closePopup() {
      document.getElementById('popup').style.display = 'none';
      document.getElementById('editForm').reset();
      document.getElementById('currentImage').style.display = 'none';

    }

    function deleteItem() {
      
        const baseUrl = "{% url 'myapp1:delete_food' 0 %}".replace('0', id);
        document.getElementById('myh').href = baseUrl;
      
    }

    
  </script>
{% endblock %}